import Layout from "@/components/layout";
import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import "node_modules/react-modal-video/scss/modal-video.scss";
import { useEffect } from "react";
import "../public/vendor/font-awesome/css/all.min.css";
import "../public/vendor/glyphter/css/golftio.css";

// slick css
import "slick-carousel/slick/slick.css";

//main css
import "@/styles/globals.scss";

export default function App({ Component, pageProps }) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  if (Component.getLayout) {
    return Component.getLayout(
      <>
        <Head>
          <title>Aisa Tennis Academy</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="aisa_icon.png" />
        </Head>
        <Component {...pageProps} />
      </>
    );
  }

  return (
    <>
      <Head>
        <title>Aisa Tennis Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="aisa_icon.png" />
      </Head>

      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
